spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/GiftCertificates
    driver_class_name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: false
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active: prod

server:
  servlet:
    context-path: /api/

ports:
  8081,
  8082,
  8083